name: release-version
on: 
  workflow_dispatch:
    inputs:
      version-type:
        type: choice
        description: 'Update version'
        required: true
        options:
          - Major
          - Minor
          - Patch
        default: 'Minor'
permissions:
  contents: write
  pull-requests: write
  packages: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
jobs:
  release:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
      
      - run: gh config set prompt disabled
      - if: github.event.inputs.version-type == 'Major'
        run: yarn version --major --no-git-tag-version
      - if: github.event.inputs.version-type == 'Minor'
        run: yarn version --minor --no-git-tag-version
      - if: github.event.inputs.version-type == 'Patch'
        run: yarn version --patch --no-git-tag-version
      - name: Extract version
        id: version-step
        uses: michmich112/extract-version@main
        with:
          # specify here the path to your version file (e.g. package.json, pom.xml...)
          version-file: "./package.json"
          schema: major.minor.patch        
      - run: | 
          git checkout -- package.json
          echo phil test begin
          echo ${{ steps.version-step.outputs.version }}
          echo phil test end
          NEW_VERSION=${{ steps.version-step.outputs.version }}
          NEW_BRANCH="PDL-v${NEW_VERSION}"
          
          yarn || exit 1
          yarn build || exit 1
        
          npm set //npm.pkg.github.com/:_authToken ${GITHUB_TOKEN}
          git config --global user.name 'Philip Lipman'
          git config --global user.email 'philip.lipman@gmail.com'
          git checkout -b ${NEW_BRANCH}
       
      - if: github.event.inputs.version-type == 'Major'        
        run: yarn version --major
      - if: github.event.inputs.version-type == 'Minor'        
        run: yarn version --minor
      - if: github.event.inputs.version-type == 'Patch'        
        run: yarn version --patch
        
      - run: |   
          NEW_VERSION=${{ steps.version-step.outputs.version }}
          NEW_BRANCH="PDL-v${NEW_VERSION}"
          echo phil test begin
          echo ${NEW_VERSION}
          echo ${NEW_BRANCH}
          echo ${BRANCH_NAME}
          
          git push -u origin "${NEW_BRANCH}"
          gh pr create --fill --title "${NEW_BRANCH} -> ${BRANCH_NAME}" --head "${NEW_BRANCH}" --base "${BRANCH_NAME}" 

