name: release-version
on: 
  workflow_dispatch:
    inputs:
      version-type:
        type: choice
        description: 'Update version'
        required: true
        options:
          - Major
          - Minor
          - Patch
        default: 'Minor'
permissions:
  contents: write
  pull-requests: write
  packages: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
      
      - run: gh config set prompt disabled
      - if: github.event.inputs.version-type == 'Minor'
        run: yarn version --minor --no-git-tag-version
      - name: Extract version
        id: version-step
        uses: michmich112/extract-version@main
        with:
          # specify here the path to your version file (e.g. package.json, pom.xml...)
          version-file: "./package.json"
          schema: major.minor.build        
      - run: | 
          echo phil test begin
          echo ${{ steps.extract_version.outputs.version }}
          echo phil test end
          NEW_VERSION=${{ steps.extract_version.outputs.version }}
          SOURCE=$(git branch --show-current)
          NEW_BRANCH="PDL-v${NEW_VERSION}"
          
          yarn || exit 1
          yarn build || exit 1
        
          npm set //npm.pkg.github.com/:_authToken ${GITHUB_TOKEN}
          git config --global user.name 'Philip Lipman'
          git config --global user.email 'philip.lipman@gmail.com'
          git checkout -b ${NEW_BRANCH}
          
          yarn version --new-version ${NEW_VERSION}
        
          git push -u origin "${NEW_BRANCH}"
          gh pr create --fill --title "${NEW_BRANCH} -> ${SOURCE}" --head "${NEW_BRANCH}" --base "${SOURCE}" 

