name: release-version
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'New Version number'
        required: true
permissions:
  contents: write
  pull-requests: write
  packages: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-deptch: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: gh config set prompt disabled
      - run: |
        SOURCE=$(git branch --show-current)


